### ISSUE TITLE
Welcome to join OpenCompass

### ISSUE THREAD

**Issue by tonysy** [yizhilll/CIF-Bench#1]
Hello,

We extend our gratitude for the exceptional work you've been doing.
We would like to extend an invitation to CIF-Bench to participate in OpenCompass, with the aim of enhancing visibility and fostering a more accessible environment for the research community.

- https://hub.opencompass.org.cn/home
- https://github.com/open-compass/opencompass

OpenCompass Team.

**Comment by yizhilll** [comment]
Hi @tonysy, thanks for expressing your interest. 

We would love to schedule a further discussion.
